#服务器端口
server:
  port: 9000
  servlet:
    encoding:             #解决中文乱码问题，同一使用UTF-8编码
      charset: UTF-8
      force: true
      enabled: true
      force-request: true
      force-response: true

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+1
  profiles:
    active: dev     # 环境配置：  dev 开发环境   test-测试环境   pro 生产环境

socketio:
  # SocketIO端口
  port: 38888
  # 连接数大小
  workCount: 100
  # 允许客户请求
  allowCustomRequests: true
  # 协议升级超时时间(毫秒)，默认10秒，HTTP握手升级为ws协议超时时间
  upgradeTimeout: 5000
  # Ping消息超时时间(毫秒)，默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 60000
  # Ping消息间隔(毫秒)，默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 10000
  # 设置HTTP交互最大内容长度
  maxHttpContentLength: 1048576
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576